security:

    password_hashers:
        #Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'plaintext'
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'


    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: /location
                always_use_default_target_path: true
            login_throttling:
                max_attempts: 2
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_LOCATION_NEW
            - ROLE_LOCATION_EDIT
            - ROLE_LOCATION_DELETE
            - ROLE_LOCATION_SHOW
            - ROLE_MEASUREMENT_NEW
            - ROLE_MEASUREMENT_EDIT
            - ROLE_MEASUREMENT_DELETE
            - ROLE_MEASUREMENT_SHOW
        ROLE_USER:
            - ROLE_LOCATION_INDEX
            - ROLE_LOCATION_SHOW
            - ROLE_MEASUREMENT_INDEX
            - ROLE_MEASUREMENT_SHOW

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4      # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
