#controllers:
#    resource:
#        path: ../src/Controller/
#        namespace: App\Controller
#    type: attribute
#    app_logout:
#        path: /logout
#        methods: GET

controllers:
    resource: ../src/Controller/
    type: attribute

kernel:
    resource: ../src/Kernel.php
    type: attribute

app_logout:
    path: /logout
    methods: GET
